{% set name = "feedgen" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9bd51c3b5e956a2a52998c3708c4d2c729f2fcc311188e1e5d3b9726393546a

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - lxml >=4.2.5
    - python-dateutil >=2.8.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - feedgen
    - feedgen.compat
    - feedgen.entry
    - feedgen.feed
    - feedgen.util
    - feedgen.version
  commands:
    - python -m feedgen atom
    - python -m feedgen rss
    - python -m feedgen podcast
    - python -m feedgen dc.atom
    - python -m feedgen syndication.atom
    - python -m feedgen syndication.rss
    - python -m feedgen torrent

about:
  home: https://github.com/lkiesow/python-feedgen
  license: BSD-2-Clause
  license_family: BSD
  license_file: license.bsd
  summary: 'Generate web feeds in both ATOM and RSS format.'
  description: |
    This module can be used to generate web feeds in both ATOM and RSS format.
    It has support for extensions.
    Included is for example an extension to produce Podcasts.
  doc_url: https://feedgen.kiesow.be/
  dev_url: https://github.com/lkiesow/python-feedgen

extra:
  recipe-maintainers:
    - nabobalis
